namespace Sabz.DataLayer.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class baseEntity : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.AccidentTbl", "Id", c => c.Int(nullable: false));
            AddColumn("dbo.AccidentTbl", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.AccidentTbl", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.AccidentTbl", "CreatedBy", c => c.String());
            AddColumn("dbo.AccidentTbl", "ModifiedBy", c => c.String());
            AddColumn("dbo.AutomobileTbl", "Id", c => c.Int(nullable: false));
            AddColumn("dbo.AutomobileTbl", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.AutomobileTbl", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.AutomobileTbl", "CreatedBy", c => c.String());
            AddColumn("dbo.AutomobileTbl", "ModifiedBy", c => c.String());
            AddColumn("dbo.AutomobileTypeTbl", "Id", c => c.Int(nullable: false));
            AddColumn("dbo.AutomobileTypeTbl", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.AutomobileTypeTbl", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.AutomobileTypeTbl", "CreatedBy", c => c.String());
            AddColumn("dbo.AutomobileTypeTbl", "ModifiedBy", c => c.String());
            AddColumn("dbo.RoutTbl", "Id", c => c.Int(nullable: false));
            AddColumn("dbo.RoutTbl", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.RoutTbl", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.RoutTbl", "CreatedBy", c => c.String());
            AddColumn("dbo.RoutTbl", "ModifiedBy", c => c.String());
            AddColumn("dbo.DriverRoutTbl", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.DriverRoutTbl", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.DriverRoutTbl", "CreatedBy", c => c.String());
            AddColumn("dbo.DriverRoutTbl", "ModifiedBy", c => c.String());
            AddColumn("dbo.DriverTbl", "Id", c => c.Int(nullable: false));
            AddColumn("dbo.DriverTbl", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.DriverTbl", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.DriverTbl", "CreatedBy", c => c.String());
            AddColumn("dbo.DriverTbl", "ModifiedBy", c => c.String());
            AddColumn("dbo.PaymentTbl", "Id", c => c.Int(nullable: false));
            AddColumn("dbo.PaymentTbl", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.PaymentTbl", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.PaymentTbl", "CreatedBy", c => c.String());
            AddColumn("dbo.PaymentTbl", "ModifiedBy", c => c.String());
            AddColumn("dbo.RepairmentTbl", "Id", c => c.Int(nullable: false));
            AddColumn("dbo.RepairmentTbl", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.RepairmentTbl", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.RepairmentTbl", "CreatedBy", c => c.String());
            AddColumn("dbo.RepairmentTbl", "ModifiedBy", c => c.String());
            AddColumn("dbo.LogRoutDriverTbl", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.LogRoutDriverTbl", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.LogRoutDriverTbl", "CreatedBy", c => c.String());
            AddColumn("dbo.LogRoutDriverTbl", "ModifiedBy", c => c.String());
            AddColumn("dbo.RegionTbl", "Id", c => c.Int(nullable: false));
            AddColumn("dbo.RegionTbl", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.RegionTbl", "ModifiedDate", c => c.DateTime());
            AddColumn("dbo.RegionTbl", "CreatedBy", c => c.String());
            AddColumn("dbo.RegionTbl", "ModifiedBy", c => c.String());
            DropColumn("dbo.AccidentTbl", "CFDate");
            DropColumn("dbo.AccidentTbl", "LFDate");
            DropColumn("dbo.AutomobileTbl", "CFDate");
            DropColumn("dbo.AutomobileTbl", "LFDate");
            DropColumn("dbo.AutomobileTypeTbl", "CFDate");
            DropColumn("dbo.AutomobileTypeTbl", "LFDate");
            DropColumn("dbo.RoutTbl", "CFDate");
            DropColumn("dbo.RoutTbl", "LFDate");
            DropColumn("dbo.DriverRoutTbl", "CFDate");
            DropColumn("dbo.DriverRoutTbl", "LFDate");
            DropColumn("dbo.DriverTbl", "CFDate");
            DropColumn("dbo.DriverTbl", "LFDate");
            DropColumn("dbo.PaymentTbl", "CFDate");
            DropColumn("dbo.PaymentTbl", "LFDate");
            DropColumn("dbo.RepairmentTbl", "CFDate");
            DropColumn("dbo.RepairmentTbl", "LFDate");
            DropColumn("dbo.LogRoutDriverTbl", "CFDate");
            DropColumn("dbo.LogRoutDriverTbl", "LFDate");
            DropColumn("dbo.RegionTbl", "CFDate");
            DropColumn("dbo.RegionTbl", "LFDate");
        }
        
        public override void Down()
        {
            AddColumn("dbo.RegionTbl", "LFDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.RegionTbl", "CFDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.LogRoutDriverTbl", "LFDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.LogRoutDriverTbl", "CFDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.RepairmentTbl", "LFDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.RepairmentTbl", "CFDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.PaymentTbl", "LFDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.PaymentTbl", "CFDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.DriverTbl", "LFDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.DriverTbl", "CFDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.DriverRoutTbl", "LFDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.DriverRoutTbl", "CFDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.RoutTbl", "LFDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.RoutTbl", "CFDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.AutomobileTypeTbl", "LFDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.AutomobileTypeTbl", "CFDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.AutomobileTbl", "LFDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.AutomobileTbl", "CFDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.AccidentTbl", "LFDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.AccidentTbl", "CFDate", c => c.DateTime(nullable: false));
            DropColumn("dbo.RegionTbl", "ModifiedBy");
            DropColumn("dbo.RegionTbl", "CreatedBy");
            DropColumn("dbo.RegionTbl", "ModifiedDate");
            DropColumn("dbo.RegionTbl", "CreatedDate");
            DropColumn("dbo.RegionTbl", "Id");
            DropColumn("dbo.LogRoutDriverTbl", "ModifiedBy");
            DropColumn("dbo.LogRoutDriverTbl", "CreatedBy");
            DropColumn("dbo.LogRoutDriverTbl", "ModifiedDate");
            DropColumn("dbo.LogRoutDriverTbl", "CreatedDate");
            DropColumn("dbo.RepairmentTbl", "ModifiedBy");
            DropColumn("dbo.RepairmentTbl", "CreatedBy");
            DropColumn("dbo.RepairmentTbl", "ModifiedDate");
            DropColumn("dbo.RepairmentTbl", "CreatedDate");
            DropColumn("dbo.RepairmentTbl", "Id");
            DropColumn("dbo.PaymentTbl", "ModifiedBy");
            DropColumn("dbo.PaymentTbl", "CreatedBy");
            DropColumn("dbo.PaymentTbl", "ModifiedDate");
            DropColumn("dbo.PaymentTbl", "CreatedDate");
            DropColumn("dbo.PaymentTbl", "Id");
            DropColumn("dbo.DriverTbl", "ModifiedBy");
            DropColumn("dbo.DriverTbl", "CreatedBy");
            DropColumn("dbo.DriverTbl", "ModifiedDate");
            DropColumn("dbo.DriverTbl", "CreatedDate");
            DropColumn("dbo.DriverTbl", "Id");
            DropColumn("dbo.DriverRoutTbl", "ModifiedBy");
            DropColumn("dbo.DriverRoutTbl", "CreatedBy");
            DropColumn("dbo.DriverRoutTbl", "ModifiedDate");
            DropColumn("dbo.DriverRoutTbl", "CreatedDate");
            DropColumn("dbo.RoutTbl", "ModifiedBy");
            DropColumn("dbo.RoutTbl", "CreatedBy");
            DropColumn("dbo.RoutTbl", "ModifiedDate");
            DropColumn("dbo.RoutTbl", "CreatedDate");
            DropColumn("dbo.RoutTbl", "Id");
            DropColumn("dbo.AutomobileTypeTbl", "ModifiedBy");
            DropColumn("dbo.AutomobileTypeTbl", "CreatedBy");
            DropColumn("dbo.AutomobileTypeTbl", "ModifiedDate");
            DropColumn("dbo.AutomobileTypeTbl", "CreatedDate");
            DropColumn("dbo.AutomobileTypeTbl", "Id");
            DropColumn("dbo.AutomobileTbl", "ModifiedBy");
            DropColumn("dbo.AutomobileTbl", "CreatedBy");
            DropColumn("dbo.AutomobileTbl", "ModifiedDate");
            DropColumn("dbo.AutomobileTbl", "CreatedDate");
            DropColumn("dbo.AutomobileTbl", "Id");
            DropColumn("dbo.AccidentTbl", "ModifiedBy");
            DropColumn("dbo.AccidentTbl", "CreatedBy");
            DropColumn("dbo.AccidentTbl", "ModifiedDate");
            DropColumn("dbo.AccidentTbl", "CreatedDate");
            DropColumn("dbo.AccidentTbl", "Id");
        }
    }
}
