// <auto-generated />
namespace Sabz.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addField2LogRoutDriver : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addField2LogRoutDriver));
        
        string IMigrationMetadata.Id
        {
            get { return "202004301238300_addField2LogRoutDriver"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
